#!/usr/bin/env bash
SLAY_SCREENSHOTS="$HOME/Screenshots"

DIRECTORIES=(
  $HOME/Development
  $HOME/Screenshots
)

step "Making directories…"
for dir in ${DIRECTORIES[@]}; do
    mkd $dir
done

echo "${indent}  ︎︎❤︎ Configuring screenshots…"
defaults write com.apple.screencapture type jpg
defaults write com.apple.screencapture location $SLAY_SCREENSHOTS
killall SystemUIServer

echo "${indent}  ︎︎❤︎ Configuring dock…"
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0;
defaults write com.apple.dock autohide-time-modifier -float 0.5;
defaults write com.apple.dock minimize-to-application -BOOL YES
killall Dock

echo "${indent}  ︎︎❤︎ Configuring screensaver…"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

echo "${indent}  ︎︎❤︎ Configuring finder"
defaults write com.apple.finder ShowPathbar -bool true # Show path bar in Finder
defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES # Show absolute path in Finder