#!/usr/bin/env bash

###############################################################################
# Screenshots                                 #
###############################################################################
echo "Configuring Screenshots"

SCREENSHOTS_FOLDER="$HOME/Screenshots"

defaults write com.apple.screencapture location $SCREENSHOTS_FOLDER

###############################################################################
# Screensaver                                 #
###############################################################################
echo "Configuring Screensaver"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

###############################################################################
# Dock                                    #
###############################################################################
echo "Configuring Dock"

defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock magnification -bool false
defaults write com.apple.dock "show-recents" -bool false
defaults write com.apple.dock tilesize -integer 36

# Set hot corners
# - 0: No Option
# - 2: Mission Control
# - 3: Show application windows
# - 4: Desktop
# - 5: Start screen saver
# - 6: Disable screen saver
# - 7: Dashboard
# - 10: Put display to sleep
# - 11: Launchpad
# - 12: Notification Center
# - 13: Lock Screen
defaults write com.apple.dock wvous-br-corner -int 5

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

# Show only open applications in the Dock
defaults write com.apple.dock static-only -bool true

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Make the animation when hiding/showing the Dock faster
defaults write com.apple.dock autohide-time-modifier -float 0.15

###############################################################################
# Trackpad & keyboard                             #
###############################################################################
echo "Configuring Trackpad & Keyboard"

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

###############################################################################
# Finder                                    #
###############################################################################
echo "Configuring Finder"

# Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Show path bar in Finder
defaults write com.apple.finder ShowPathbar -bool true

# Show absolute path in Finder
defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES

###############################################################################
# Menu Bar                                  #
###############################################################################
echo "Configuring Menu Bar"

# Show Battery Percentage on the meny bar
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Show volume in menu bar
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.volume" -bool true

###############################################################################
# Photos                                    #
###############################################################################
echo "Configuring Bluetooth"

# Increase sound quality for Bluetooth headphones/headsets
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

defaults write com.apple.screencapture location $HOME/Desktop/screenshots

###############################################################################

###############################################################################
# Mac App Store                                 #
###############################################################################
echo "Configuring Mac App Store"

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Automatically download apps purchased on other Macs
defaults write com.apple.SoftwareUpdate ConfigDataInstall -int 1

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true

###############################################################################

###############################################################################
# Photos                                    #
###############################################################################
echo "Configuring Photos"

# Don’t open Photos when plugging in an iPhone
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool YES

###############################################################################

echo "Killing all affected apps to apply the changes"

APPS=(
  cfprefsd
  Dock
  Finder
  SystemUIServer
)

# Kill all affected apps
for app in ${APPS[@]}; do
  killall "${app}" > /dev/null 2>&1
done